---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: fe-deploy 
  labels: 
    name: fe-deploy 
    app: bc16-app 
spec: 
  selector: 
    matchLabels: 
      name: frontend-pod 
      app: bc16-app 
  template: 
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
        app: bc16-app
    spec:
      containers:
      - name: frontend
        image: rishmitha/ingressfe2
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-deploy
  labels:
    name: job-deploy
    app: bc16-app
spec:
  selector:
    matchLabels:
      name: job-pod
      app: bc16-app
  template:
    metadata:
      name: job-pod
      labels:
        name: job-pod
        app: bc16-app
    spec:
      containers:
      - name: job
        image: rishmitha/ingressjsbe
        ports:
          - containerPort: 8082
        env: 
          - name: "SPRING_DATASOURCE_URL"
            value: "jdbc:postgresql://db:5432/postgres"
          - name: "SPRING_DATASOURCE_USERNAME"
            value: "postgres"
          - name: "SPRING_DATASOURCE_PASSWORD"
            value: "1234" 
          - name: "SPRING_JPA_HIBERNATE_DDL_AUTO"
            value: "update" 
#          - name: "ORG_URL"
#            value: "http://18.223.182.178:30897/api/v1/organizations"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org-deploy
  labels:
    name: org-deploy
    app: bc16-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: org-pod
      app: bc16-app
  template:
    metadata:
      name: org-pod
      labels:
        name: org-pod
        app: bc16-app
    spec:
      containers:
      - name: org
        image: rishmitha/orgsvc
        ports:
        - containerPort: 8081
        env: 
          - name: "SPRING_DATASOURCE_URL"
            value: "jdbc:postgresql://db:5432/postgres"
          - name: "SPRING_DATASOURCE_USERNAME"
            value: "postgres"
          - name: "SPRING_DATASOURCE_PASSWORD"
            value: "1234"
          - name: "SPRING_JPA_HIBERNATE_DDL_AUTO"
            value: "update" 
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: postgres-deploy 
  labels: 
    name: postgres-deploy 
    app: bc16-app 
spec: 
  serviceName: db
  selector: 
    matchLabels: 
      name: postgres-pod 
      app: bc16-app 
  template: 
    metadata: 
      name: postgres-pod 
      labels: 
        name: postgres-pod 
        app: bc16-app 
    spec: 
      containers: 
      - name: postgres 
        image: postgres 
        ports: 
          - containerPort: 5432 
        env: 
          - name: "POSTGRES_USER"
            value: "postgres"
          - name: "POSTGRES_PASSWORD"
            value: "1234"
          - name: "POSTGRES_DB"
            value: "postgres"
        volumeMounts:
            - name: my-pv
              mountPath: /var/lib/postgresql/data
      volumes:
      - name: my-pv
        persistentVolumeClaim:
          claimName: bc16-pvc

